HSStats/Models/Match.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HSStats.Models
{
    public class Match
    {
        public int MatchID { get; set; }

        [Required]        
        public Modes? Mode { get; set; }

        [Required]
        [Display(Name = "As")]
        public Heroes? MyHero { get; set; }

        [Required]
        [Display(Name = "Vs")]
        public Heroes? OpponentHero { get; set; }

        [Required]
        [Display(Name="Your turn")]
        public Turns? Turn { get; set; }

        [Required]
        public Results? Result { get; set; }

        [Display(Name = "Time of the match")]        
        public DateTime MatchTime { get; set; }

        public int? ArenaID { get; set; }
    }

    public enum Heroes : byte { Druid, Hunter, Mage, Paladin, Priest, Rogue, Shaman, Warlock, Warrior };

    public enum Results : byte { Win, Defeat, Draw, Unknown };

    public enum Modes: byte { Ranked, Arena, Unranked }

    public enum Turns { Unknown, [Display(Name = "Go first")] GoFirst, [Display(Name = "Go second")] GoSecond }
}

HSStats/Controllers/ArenaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HSStats.Models;

namespace HSStats.Controllers
{
    public class ArenaController : Controller
    {
        private HSStatsDbContext db = new HSStatsDbContext();
        //
        // GET: /Arena/
        public ActionResult Index()
        {
            var arenas = from a in db.Arenas select a;
            return View(arenas);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Arena arena)
        {
            if(ModelState.IsValid)
            {
                arena.StartDate = DateTime.Now;
                db.Arenas.Add(arena);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(arena);
        }

        public ActionResult AddMatch(int id, Heroes myHero)
        {
            Match match = new Match() {  ArenaID = id, Mode = Modes.Arena, MyHero = myHero };        
            return View(match);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMatch(Match match)
        {
            if(ModelState.IsValid)
            {
                Arena arena = db.Arenas.Find(match.ArenaID);
                if ( match.Result == Results.Win )
                {                    
                    arena.Wins = arena.Wins+1;
                }
                if ( match.Result == Results.Defeat )
                {
                    arena.Defeats = arena.Defeats+1;
                }
                match.MatchTime = DateTime.Now;
                db.Matches.Add(match);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(match);
        }

        public ActionResult AddRewards(int? id)
        {
            if ( id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arena arena = db.Arenas.Find(id);
            if ( arena == null )
            {
                return HttpNotFound();
            }
            return View(arena);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRewards(Arena arena)
        {
            if(ModelState.IsValid)
            {
                db.Entry(arena).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(arena);
        }

        public ActionResult Delete(int? id)
        {
            if ( id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arena arena = db.Arenas.Find(id);            
            if ( arena == null )
            {
                return HttpNotFound();
            }
            return View(arena);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Arena arena = db.Arenas.Find(id);            
            db.Arenas.Remove(arena);
            foreach (var match in db.Matches.Where(m=>m.ArenaID == id).Select(m => m))
            {
                db.Matches.Remove(match);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if ( id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arena arena = db.Arenas.Find(id);            
            if ( arena == null )
            {
                return HttpNotFound();
            }
            return View(arena);
        }

        [ChildActionOnly]
        public ActionResult ListOfMatches(int? id)
        {
            if ( id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var matches = db.Matches.Where(m => m.ArenaID == id).Select(m => m);
            if(matches == null)
            {
                return HttpNotFound();
            }
            return PartialView("_ListOfMatches", matches);
        }

	}
}

HSStats/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HSStats.Models;
using System.Data.Entity.Infrastructure;

namespace HSStats.Controllers
{
    public class MatchController : Controller
    {
        private HSStatsDbContext db = new HSStatsDbContext();

        // GET: /Match/
        public ActionResult Index(Modes? mode, Heroes? myHero, Heroes? opponentHero, Turns? turn, Results? result, int? arenaID)
        {
            var matches = from m in db.Matches select m;

            if(arenaID != null)
            {
                matches = matches.Where(m => m.ArenaID == arenaID);
            }

            if(mode != null)
            {
                matches = matches.Where(m => m.Mode == mode);
            }

            if(myHero != null)
            {
                matches = matches.Where(m => m.MyHero == myHero);
            }
            
            if(opponentHero != null)
            {
                matches = matches.Where(o => o.OpponentHero == opponentHero);
            }

            if(turn != null)
            {
                matches = matches.Where(y => y.Turn == turn);
            }

            if(result != null)
            {
                matches = matches.Where(r => r.Result == result);
            }

            return View(matches.OrderByDescending(m => m.MatchTime));
        }

        // GET: /Match/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        // GET: /Match/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Match/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="MatchID,Mode,MyHero,OpponentHero,Turn,Result,MatchTime,ArenaID")] Match match)
        {
            if (ModelState.IsValid)
            {
                match.MatchTime = DateTime.Now;
                db.Matches.Add(match);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(match);
        }

        // GET: /Match/Edit/5
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = returnUrl;
            return View(match);
        }

        // POST: /Match/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="MatchID,Mode,MyHero,OpponentHero,Turn,Result,MatchTime,ArenaID")] Match match, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if(match.ArenaID != null)
                {
                    Match original = db.Matches.Find(match.MatchID);
                    if ( match.Result != original.Result )
                    {
                        Arena arena = db.Arenas.Find(match.ArenaID);
                        if ( match.Result == Results.Win && arena.Wins < 12)
                        {
                            arena.Wins = arena.Wins + 1;
                            arena.Defeats = arena.Defeats - 1;
                        }
                        else if ( match.Result == Results.Win && arena.Wins > 11 )
                        {
                            ViewBag.Message = "Number of wins on the single arena can't be more than 12.";
                            return View(match);
                        }

                        if ( match.Result == Results.Defeat && arena.Defeats < 3)
                        {
                            arena.Defeats = arena.Defeats + 1;
                            arena.Wins = arena.Wins - 1;
                        }
                        else if ( match.Result == Results.Defeat && arena.Defeats > 2 )
                        {
                            ViewBag.Message = "Number of defeats on the single arena can't be more than 3.";
                            return View(match);
                        }
                    }
                    ((IObjectContextAdapter)db).ObjectContext.Detach(original);
                }                
                db.Entry(match).State = EntityState.Modified;
                db.SaveChanges();
                if ( returnUrl != null )
                {
                    return Redirect(returnUrl);
                }
                return RedirectToAction("Index");
            }
            return View(match);
        }

        // GET: /Match/Delete/5
        public ActionResult Delete(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = returnUrl;
            return View(match);
        }

        // POST: /Match/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, string returnUrl)
        {
            Match match = db.Matches.Find(id);
            if(match.ArenaID != null)
            {
                Arena arena = db.Arenas.Find(match.ArenaID);
                if(match.Result == Results.Win)
                {
                    arena.Wins = arena.Wins - 1;
                }
                else if(match.Result == Results.Defeat)
                {
                    arena.Defeats = arena.Defeats - 1;
                }
            }
            db.Matches.Remove(match);
            db.SaveChanges();
            
            if ( returnUrl != null )
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index");            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [ChildActionOnly]
        public ActionResult Search(Match match)
        {
            return PartialView("_Search", match);
        }
    }
}

HSStats/Views/Match/Create.cshtml
@model HSStats.Models.Match

@{
    ViewBag.Title = "Create match";
}

<h2>Create match</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Mode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.EnumDropDownListFor(model => model.Mode)
                @Html.ValidationMessageFor(model => model.Mode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MyHero, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.MyHero)                
                @Html.ValidationMessageFor(model => model.MyHero)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpponentHero, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.OpponentHero)                
                @Html.ValidationMessageFor(model => model.OpponentHero)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Turn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Turn)
                @Html.ValidationMessageFor(model => model.Turn)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Result)                
                @Html.ValidationMessageFor(model => model.Result)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HSStats/Views/Match/Delete.cshtml
@model HSStats.Models.Match

@{
    ViewBag.Title = "Delete match";
}

<h2>Delete match</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MyHero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyHero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpponentHero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpponentHero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatchTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MatchTime)
        </dd>

    </dl>

    @using ( Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }) )
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index") |
            @if ( Model.ArenaID != null )
            {
                @Html.ActionLink("Back to arena details", "Details", "Arena", new { id = Model.ArenaID }, null)
            }
        </div>
    }
</div>

HSStats/Views/Match/Details.cshtml
@model HSStats.Models.Match

@{
    ViewBag.Title = "Match details";
}

<h2>Match details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MyHero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyHero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpponentHero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpponentHero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatchTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatchTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MatchID, ReturnUrl = Request.Url.PathAndQuery }) |
    @Html.ActionLink("Back to List", "Index") |
    @if(Model.ArenaID != null)
    {
        @Html.ActionLink("Back to arena details", "Details", "Arena", new { id = Model.ArenaID }, null)
    }
</p>

HSStats/Views/Match/Edit.cshtml
@model HSStats.Models.Match

@{
    ViewBag.Title = "Edit match";
}

<h2>Edit match</h2>

<p class="validation-summary-errors">@ViewBag.Message</p>
@using ( Html.BeginForm(new {ReturnUrl = ViewBag.ReturnUrl}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MatchID)
        @Html.HiddenFor(model => model.MatchTime)
        @Html.HiddenFor(model => model.ArenaID)

        @if ( Model.Mode != HSStats.Models.Modes.Arena )
        { 
            <div class="form-group">
                @Html.LabelFor(model => model.Mode, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Mode)
                    @Html.ValidationMessageFor(model => model.Mode)
                </div>
            </div>
            
            <div class="form-group">
                @Html.LabelFor(model => model.MyHero, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.MyHero)
                    @Html.ValidationMessageFor(model => model.MyHero)
                </div>
            </div>
        }
        else
        {
            @Html.HiddenFor(model => model.Mode)
            @Html.HiddenFor(model => model.MyHero)
        }

        <div class="form-group">
            @Html.LabelFor(model => model.OpponentHero, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.OpponentHero)
                @Html.ValidationMessageFor(model => model.OpponentHero)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Turn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Turn)
                @Html.ValidationMessageFor(model => model.Turn)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Result)
                @Html.ValidationMessageFor(model => model.Result)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatchTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MatchTime)
            </div>        
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index") |
    @if ( Model.ArenaID != null )
    {
        @Html.ActionLink("Back to arena details", "Details", "Arena", new { id = Model.ArenaID }, null)
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HSStats/Views/Match/Index.cshtml
@model IEnumerable<HSStats.Models.Match>

@{
    ViewBag.Title = "List of the matches";
}

<h2>List of matches</h2>

<p>
    @Html.ActionLink("Create new match", "Create")
    @Html.Action("Search", "Match")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Mode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MyHero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpponentHero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Turn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatchTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Mode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MyHero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpponentHero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Turn)        
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Result)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MatchTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MatchID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MatchID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MatchID })
        </td>
    </tr>
}

</table>

HSStats/Views/Match/_Search.cshtml
@model HSStats.Models.Match

@using ( Html.BeginForm("Index", "Match"))
{
    @Html.EnumDropDownListFor(model => model.Mode, "Mode")
    @Html.EnumDropDownListFor(model => model.MyHero, "AS")
    @Html.EnumDropDownListFor(model => model.OpponentHero, "VS")
    @Html.EnumDropDownListFor(model => model.Turn, "Your Turn")
    @Html.EnumDropDownListFor(model => model.Result, "Result")
    <input type="submit" value="Filter" />
}